fix _triton.runtime calls
Summary:
triton_mlir does not have `_triton.runtime.cc`, `_triton.runtime.num_sm`, `_triton.runtime.clock_rate`.

get test error for `protoquant/tests:gemm_e2e_tests - test_ngemm_e2e_cuda`
error stack
```
AttributeError: module 'triton._C.libtriton.triton.runtime' has no attribute 'cc'
  File "/usr/local/fbcode/platform010/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/local/fbcode/platform010/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/local/fbcode/platform010/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/protoquant/tests/gemm_e2e_tests.py", line 103, in test_ngemm_e2e_cuda
    out = gemm(mat1, mat2)
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/protoquant/gemm.py", line 20, in gemm
    return matmul(mat1, mat2.t())
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/protoquant/src/triton/matmul.py", line 270, in forward
    return _matmul._call(a, b)
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/protoquant/src/triton/matmul.py", line 250, in _call
    _kernel[grid](
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/triton/runtime/autotuner.py", line 75, in run
    pruned_configs = self.prune_configs(kwargs)
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/triton/runtime/autotuner.py", line 95, in prune_configs
    pruned_configs = self.early_config_prune(self.configs, self.nargs)
  File "/re_cwd/buck-out/v2/gen/fbcode/61e59afdb6f78901/protoquant/tests/__gemm_e2e_tests__/gemm_e2e_tests#link-tree/protoquant/src/triton/matmul_perf_model.py", line 127, in early_config_prune
    cc = _triton.runtime.cc(backend, device)
```

this file is copied from https://github.com/openai/triton/blob/5a786cf7786729b3af6d18ce3725454484ee15e3/python/triton/ops/matmul_perf_model.py, just adapt the new code with lint

Reviewed By: nmacchioni

Differential Revision: D44005310

fbshipit-source-id: 76aaad40c9a5d45d4a088d850a836bc9b5498085